import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { access, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { server, setup, root, manifest, transactionHash } from './harness.mjs';

const report = { date: new Date().toISOString(), target: 'committed production export under /preview/', mock: true, checks: [], browser: '', consoleErrors: [], screenshots: [], measurements: [] };
const check = (name, detail = '') => { report.checks.push({ name, status: 'passed', detail }); console.log(`PASS ${name}`); };
let executablePath = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
const supplied = '/opt/imd-worker/local/imd-browser-tool/ms-playwright/chromium-1246/chrome-linux64/chrome';
if (!executablePath) { try { await access(supplied); executablePath = supplied; } catch { /* Use Playwright's installed browser on other machines. */ } }
const browser = await chromium.launch({ executablePath, headless: true, args: ['--no-sandbox'] });
report.browser = browser.version();
const preview = await server();
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
context.setDefaultTimeout(15000);
context.setDefaultNavigationTimeout(15000);
const errors = [];
const resourceFailures = [];
context.on('page', page => {
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.url().startsWith(preview.url) && response.status() >= 400) resourceFailures.push({ url:response.url(),status:response.status() }); });
});
try {
  const page = await context.newPage();
  const fixture = await setup(page);
  await page.goto(preview.url);
  await expect(page.getByText('Pool state · block')).toBeVisible();
  await expect(page.getByRole('heading', { name: '0.012345 ETH' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Donate accrued ETH' })).toBeDisabled();
  check('Disconnected reads and transaction gating');
  await page.getByRole('button', { name: 'Connect wallet', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Switch to Sepolia' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Donate accrued ETH' })).toBeDisabled();
  await page.getByRole('button', { name: 'Switch to Sepolia' }).click();
  await expect(page.getByRole('button', { name: 'Donate accrued ETH' })).toBeEnabled();
  const requests = await page.evaluate(() => window.__walletCalls);
  const addition = requests.find(r => r.method === 'wallet_addEthereumChain');
  expect(addition.params[0]).toEqual(manifest.walletAddChain);
  expect(requests.filter(r => r.method === 'wallet_switchEthereumChain')).toHaveLength(2);
  check('Unknown-chain switch → exact add-chain payload → switch');
  await page.getByRole('button', { name: 'Get quote' }).click();
  await expect(page.getByLabel('You pay', { exact: true })).toBeFocused();
  await expect(page.locator('#amount')).toHaveAttribute('aria-invalid', 'true');
  check('Invalid input focuses the labeled field and explains precision');
  await page.locator('#amount').fill('0.001');
  await page.getByRole('button', { name: 'Get quote' }).click();
  await expect(page.getByRole('button', { name: 'Swap ETH for ETHF' })).toBeEnabled();
  await expect(page.getByText('0.000005 ETH', { exact: true })).toBeVisible();
  expect(fixture.simulations.find(s => s.functionName === 'quoteExactInputSingle').to).toBe(manifest.network.uniswapV4.quoter);
  check('Native ETH quote through configured V4Quoter and ceiling fee preview');
  await page.evaluate(() => window.__walletFixture.rejected = true);
  await page.getByRole('button', { name: 'Swap ETH for ETHF' }).click();
  await expect(page.getByRole('alert')).toContainText('declined');
  expect(fixture.requests).toHaveLength(0);
  await page.evaluate(() => window.__walletFixture.rejected = false);
  check('Wallet rejection is recoverable and does not submit');
  fixture.revertSimulation = true;
  await page.getByRole('button', { name: 'Swap ETH for ETHF' }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  expect(fixture.requests).toHaveLength(0);
  fixture.revertSimulation = false;
  check('Failed simulation prevents wallet broadcast');
  fixture.pending = true;
  await page.getByRole('button', { name: 'Swap ETH for ETHF' }).click();
  await expect(page.getByText('Pending · Swap')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Donate accrued ETH' })).toBeDisabled();
  expect(fixture.requests[0].to.toLowerCase()).toBe(manifest.poolSwapTest.toLowerCase());
  expect(BigInt(fixture.requests[0].value)).toBe(1000000000000000n);
  const swap = fixture.simulations.filter(s => s.functionName === 'swap').at(-1);
  expect(swap.args[1].amountSpecified).toBe(-1000000000000000n);
  expect(swap.args[1].sqrtPriceLimitX96 < 79299443975792720780679863727831n).toBeTruthy();
  expect(swap.args[3]).toBe('0x');
  expect(fixture.simulations.filter(s => s.functionName === 'approve')).toHaveLength(0);
  fixture.pending = false;
  await expect(page.getByText('Confirmed · Swap')).toBeVisible({ timeout: 10000 });
  check('Buy uses PoolSwapTest, exact native value, negative input, price limit, empty hookData; no approval');
  await page.getByRole('button', { name: 'Donate accrued ETH' }).click();
  await expect(page.getByText('Confirmed · Donation')).toBeVisible({ timeout: 10000 });
  await expect(page.getByRole('heading', { name: '0 ETH', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Donate accrued ETH' })).toBeDisabled();
  const donation = fixture.simulations.find(s => s.functionName === 'donateFees');
  expect(donation.args[0].hooks.toLowerCase()).toBe(manifest.contracts.find(c => c.name === 'ETHOnlyFeeHook').address);
  check('Donate simulates, submits without personal ETH, refreshes totals and displays receipt');
  await page.getByRole('button', { name: 'Sell ETHF' }).click();
  await page.locator('#amount').fill('1000');
  await page.getByRole('button', { name: 'Get quote' }).click();
  await expect(page.getByRole('button', { name: 'Approve ETHF for this amount' })).toBeEnabled();
  await page.getByRole('button', { name: 'Approve ETHF for this amount' }).click();
  await expect(page.getByText('Confirmed · Token approval')).toBeVisible({ timeout: 10000 });
  const approval = fixture.simulations.find(s => s.functionName === 'approve');
  expect(approval.args[0].toLowerCase()).toBe(manifest.poolSwapTest.toLowerCase());
  expect(approval.args[1]).toBe(1000n * 10n ** 18n);
  await page.getByRole('button', { name: 'Get quote' }).click();
  await expect(page.getByRole('button', { name: 'Swap ETHF for ETH' })).toBeEnabled();
  await page.getByRole('button', { name: 'Swap ETHF for ETH' }).click();
  await expect(page.getByText('Confirmed · Swap')).toBeVisible({ timeout: 10000 });
  const sell = fixture.simulations.filter(s => s.functionName === 'swap').at(-1);
  expect(sell.args[1].zeroForOne).toBe(false);
  expect(sell.args[1].sqrtPriceLimitX96 > 79299443975792720780679863727831n).toBeTruthy();
  expect(BigInt(sell.value ?? '0x0')).toBe(0n);
  check('Sell requires a separate exact-amount router approval, then sends no ETH');
  await page.getByRole('button', { name: 'Get quote' }).click();
  await expect(page.getByRole('button', { name: 'Swap ETHF for ETH' })).toBeEnabled();
  await page.getByLabel('Price tolerance').selectOption('300');
  await expect(page.getByRole('button', { name: 'Swap ETHF for ETH' })).toBeDisabled();
  check('Changed tolerance invalidates an existing quote');
  await page.getByRole('button', { name: 'Get quote' }).click();
  await expect(page.getByRole('button', { name: 'Swap ETHF for ETH' })).toBeEnabled();
  await page.clock.install();
  await page.clock.fastForward(46000);
  await expect(page.getByRole('button', { name: 'Swap ETHF for ETH' })).toBeDisabled();
  await expect(page.getByText('Quote expired. Refresh before continuing.')).toBeVisible();
  check('Quote expiry blocks signing after 45 seconds');
  await page.clock.resume();
  await page.evaluate(() => window.__changeAccount());
  await expect(page.getByRole('button', { name: 'Connect wallet', exact: true })).toBeVisible();
  check('Wallet account change invalidates quote and connected balances');
  await page.close();

  // Fresh page for stable visual and accessibility evidence. All values below are fixture data.
  const visual = await context.newPage();
  await setup(visual, { chain: manifest.walletAddChain.chainId, connected: true, unknownChain: false });
  await visual.goto(preview.url);
  await expect(visual.getByRole('button', { name: 'Donate accrued ETH' })).toBeEnabled();
  await visual.locator('#amount').fill('0.001');
  await visual.getByRole('button', { name: 'Get quote' }).click();
  await expect(visual.getByRole('button', { name: 'Swap ETH for ETHF' })).toBeEnabled();
  for (const width of [1440, 800, 390, 320]) {
    await visual.setViewportSize({ width, height: 1000 });
    expect(await visual.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    const scan = await new AxeBuilder({ page: visual }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
    expect(scan.violations.map(v => ({ id:v.id, nodes:v.nodes.map(n => ({ target:n.target, summary:n.failureSummary })) }))).toEqual([]);
    check(`Production export at ${width}px: no horizontal overflow; axe WCAG A/AA scan clean`);
    if ([1440, 390, 320].includes(width)) {
      const path = `docs/evidence/${width === 1440 ? 'desktop' : `mobile-${width}`}.png`;
      await visual.screenshot({ path: resolve(root, path), fullPage: true }); report.screenshots.push({ path, width, data: 'mock wallet and RPC' });
    }
  }
  await visual.setViewportSize({ width: 1440, height: 1000 });
  await visual.locator('#amount').focus();
  await visual.keyboard.press('Tab');
  await expect(visual.getByLabel('Price tolerance')).toBeFocused();
  await visual.keyboard.press('Tab');
  await expect(visual.getByRole('button', { name: 'Refresh quote' })).toBeFocused();
  await visual.keyboard.press('Enter');
  await expect(visual.getByRole('button', { name: 'Swap ETH for ETHF' })).toBeEnabled();
  await visual.locator('#amount').focus();
  await visual.screenshot({ path: resolve(root, 'docs/evidence/focus.png'), fullPage: true });
  report.screenshots.push({ path: 'docs/evidence/focus.png', width: 1440, data: 'keyboard focus on amount field' });
  check('Keyboard field → tolerance → quote flow and visible focus screenshot');
  await visual.emulateMedia({ reducedMotion: 'reduce' });
  expect(await visual.getByRole('button', { name: 'Refresh quote' }).evaluate(el => getComputedStyle(el).transitionDuration)).toBe('0s');
  check('Reduced motion removes press transitions');
  await visual.evaluate(() => document.documentElement.style.fontSize = '32px');
  expect(await visual.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await visual.evaluate(() => document.documentElement.style.fontSize = '');
  check('200% root font-size reflow (not browser-native zoom)');
  report.measurements = await visual.evaluate(() => {
    function lum(color) { const rgb = color.match(/[\d.]+/g).slice(0,3).map(Number).map(v => { v/=255; return v<=.04045 ? v/12.92 : ((v+.055)/1.055)**2.4; }); return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722; }
    return ['.button.primary', '.intro-copy', '.metric.accrued .caption', '.amount-box .caption', '.testnet-note'].map(selector => {
      const el=document.querySelector(selector), style=getComputedStyle(el); let node=el, bg=style.backgroundColor;
      while (bg==='rgba(0, 0, 0, 0)' && node.parentElement) { node=node.parentElement; bg=getComputedStyle(node).backgroundColor; }
      const a=lum(style.color), b=lum(bg); return { selector, foreground:style.color, background:bg, ratio:Number(((Math.max(a,b)+.05)/(Math.min(a,b)+.05)).toFixed(2)) };
    });
  });
  expect(report.measurements.every(m=>m.ratio>=4.5)).toBeTruthy();
  check('Measured rendered text/background pairs meet 4.5:1');
  await visual.close();

  const noWallet = await context.newPage(); await setup(noWallet); await noWallet.addInitScript(() => { delete window.ethereum; }); await noWallet.goto(preview.url);
  await noWallet.getByRole('button', { name: 'Connect wallet', exact: true }).click(); await expect(noWallet.getByRole('alert')).toContainText('No browser wallet found');
  check('Missing browser wallet explains recovery');
  await noWallet.close();
  const empty = await context.newPage(); await setup(empty, { accrued: 0n, liquidity: 0n, chain: manifest.walletAddChain.chainId, connected: true }); await empty.goto(preview.url);
  await expect(empty.getByText('No fees are ready yet.')).toBeVisible(); await expect(empty.getByRole('button', { name: 'Donate accrued ETH' })).toBeDisabled();
  check('Zero accrued ETH cannot be donated');
  await empty.close();
  const noLiquidity = await context.newPage(); await setup(noLiquidity, { liquidity: 0n, chain: manifest.walletAddChain.chainId, connected: true }); await noLiquidity.goto(preview.url);
  await expect(noLiquidity.getByText('No liquidity is in range. Fees will wait until it returns.')).toBeVisible(); await expect(noLiquidity.getByRole('button', { name: 'Donate accrued ETH' })).toBeDisabled();
  check('No in-range liquidity preserves claims and disables donation');
  await noLiquidity.close();
  const failed = await context.newPage(); const failure = await setup(failed, { emptyCode: true }); await failed.goto(preview.url);
  await expect(failed.getByRole('alert')).toContainText('no code'); await expect(failed.getByRole('button', { name: 'Get quote' })).toBeDisabled(); failure.emptyCode = false;
  await failed.getByRole('button', { name: 'Refresh state' }).click(); await expect(failed.getByText('Pool state · block')).toBeVisible();
  check('Missing contract code blocks actions; retry recovers');
  failure.rpcFailure = true;
  await failed.getByRole('button', { name: 'Refresh state' }).click();
  await expect(failed.getByRole('alert')).toBeVisible();
  await expect(failed.getByRole('button', { name: 'Get quote' })).toBeDisabled();
  failure.rpcFailure = false;
  await failed.getByRole('button', { name: 'Refresh state' }).click();
  await expect(failed.getByRole('alert')).toHaveCount(0);
  failure.logsFail = true;
  await failed.getByRole('button', { name: 'Refresh state' }).click();
  await expect(failed.getByText('Recent donation events could not load.')).toBeVisible();
  check('RPC outage blocks actions; retry recovers; log failure preserves lifetime totals');
  await failed.close();
  const tampered = await context.newPage(); await setup(tampered);
  await tampered.route('**/abi/ETHF.json', route => route.fulfill({ contentType: 'application/json', body: '[]' })); await tampered.goto(preview.url);
  await expect(tampered.getByRole('alert')).toContainText('ABI verification failed');
  check('Runtime ABI hash mismatch blocks app initialization');
  report.consoleErrors = errors;
  expect(errors).toEqual([]);
  expect(resourceFailures).toEqual([]);
  report.resourceFailures = resourceFailures;
  check('No uncaught browser JavaScript errors across all scenarios');
  report.status = 'passed';
} catch (e) {
  report.status = 'failed'; report.failure = e.stack; throw e;
} finally {
  await writeFile(resolve(root, 'docs/evidence/browser-results.json'), JSON.stringify(report, null, 2) + '\n');
  await context.close(); await browser.close(); await preview.close();
}
